### ISSUE TITLE
Connexion bug

### ISSUE THREAD

**Issue by PapillonAudrey** [digio-ch/pbs-healthcheck-core#84] opened 2023-04-18 14:10 UTC
**Describe the bug**

Two different users reported the impossibility to connect to the tool. They click to "connect with Midata" and are redirected to the same page in a loop. They were able to connect in the past. They reported that they discovered the bug first in january but are not regular users, so maybe it appeared sooner.

https://user-images.githubusercontent.com/113099749/232803642-c423bc89-00ac-4c3a-b827-9dd93a5b0c5d.mov

**Reproducing the bug/idea of causes**

I am not sure, but I think that it is the behavior occuring when "security conditions" are not fulfilled : for example when we try to connect with a foreign IP. 

**Environment**

- Version: latest,
- Environment: google chrome version 108.0.5359.124, safari Version 15.6 (17613.3.9.1.5) et firefox version 108.0.1.

**Comment by PapillonAudrey** [comment] 2023-04-18 14:11
For further investigation, what are the IP-conditions for the users ? Did they changed in the latest releases ?

**Comment by vouillamoz** [comment] 2023-04-19 06:34
@PapillonAudrey Currently HC does not have any restrictions on the client's IP address. I tested the prod and stage environment and both are working as expected. It looks like a cookie issue. Please advice the user to remove all cookies for this site and to try again.

**Comment by fuzoh** [comment] 2023-05-23 11:40
I think i have the same bug.

Y can make all the oauth process without problems, but, at the end of the process, when the `https://hc.scout.ch/api/v1/oauth/v2/code` endpoint is called, i always get the same error :
```
{"code":500,"message":"Ein Fehler ist aufgetreten, versuche es sp\u00e4ter nochmals."}
```

Heres two videos, one when im already connected to `db.scout.ch`, another when i have to make the entire process. The error is exactly the same on the two cases.


https://github.com/digio-ch/pbs-healthcheck-core/assets/24266957/0cae71d8-b922-4ce1-98bc-7caa6f51fcb7


https://github.com/digio-ch/pbs-healthcheck-core/assets/24266957/d2f68292-0f9e-4ded-b9f8-b2d7e74d7bbe

**Comment by vouillamoz** [comment] 2023-05-23 11:42
@fuzoh thanks for your detailed bug report. we will investigate this error a bit deeper.

**Comment by vouillamoz** [comment] 2023-05-24 07:24
@fuzoh Can you please provide me your username securely here: https://www.transferly.swiss/t/d094a4fd-24b2-4579-bdb4-bf68e13b15d8#ae22b65a68413ffdc683fd33d17fb43c in order I can check the logs and your permissions?

**Comment by vouillamoz** [comment] 2023-06-05 08:03
https://digio-ltd.atlassian.net/browse/HC-231

**Comment by PapillonAudrey** [comment] 2023-08-08 08:02
@vouillamoz, can we close this issue with the new release ?

**Comment by vouillamoz** [comment] 2023-08-11 09:17
@PapillonAudrey if the issue is resolved after your testing you can close it, yes.

**Closed** 2023-08-14 08:03 UTC
Labels: bug
